# Site settings
title: "Dawid Krysa resume"
description: "A resume using Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Dawid Krysa"
resume_title:                   "Business Analyst"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "dawikry518@student.polsl.pl"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+48796011851"
resume_contact_address:         "Zabrze"

resume_header_contact_info:     "Zabrze • dawikry518@student.polsl.pl"
display_header_contact_info:    "true"

resume_header_intro: "<p>Motivated ICT student with experience in analytical work for telecommunication companies in  Norway, Denmark, Sweden, and Switzerland. In my work, I focus on implementing modern customized solutions and preparing HLD and LLD documentation for customers.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
# resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/dawidkrysa"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/dawid-krysa"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
